name: Event Log Service CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  OSSPI_BID: '2279'
  OSSPI_PRODUCT_VERSION: main
  OSSPI_RID: '000'
  ASPNETCORE_ENVIRONMENT: production
  JAVA_HOME: /usr/lib/jvm/adoptopenjdk-11-hotspot

jobs:
  update-build-status:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update build status on GitHub
      run: |
        curl -v POST "${{ secrets.GITHUB_WEBHOOK_URL }}" \
        --header 'Accept: application/vnd.github+json' \
        --header 'x-github-token: ${{ secrets.GITHUB_TOKEN }}' \
        --header 'Content-Type: application/json' \
        --data '{
          "event_type": "build_status",
          "client_payload": {
            "build_result_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "context": "${{ github.workflow }}",
            "commit_id": "${{ github.sha }}",
            "build_status": "InProgress",
            "build_plan_key": "${{ github.run_id }}",
            "build_number": "${{ github.run_number }}",
            "git_url": "${{ github.repository }}"
          }
        }'

  local-build:
    runs-on: ubuntu-latest
    needs: update-build-status
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Inject environment variables
      run: |
        echo "ASPNETCORE_ENVIRONMENT=Production" >> $GITHUB_ENV
        echo "TEST_AGAINST_REMOTE=false" >> $GITHUB_ENV
        echo "StartLocalKafkaContainer=true" >> $GITHUB_ENV
        echo "StartLocalDatabaseContainer=true" >> $GITHUB_ENV

    - name: Make .sh files executable
      run: ./bamboo-specs/scripts/common/set_permission.sh

    - name: Clean Docker
      run: ./bamboo-specs/scripts/common/docker_clean_rm.sh

    - name: Build and Test with Sonar
      run: ./build.sh --runSonar=true

    - name: MSTest Parser
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/test-results/*.trx'

    - name: Upload Log Files
      uses: actions/upload-artifact@v2
      with:
        name: log-files
        path: '**/*.log'

  docker-build:
    runs-on: ubuntu-latest
    needs: local-build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Inject environment variables
      run: |
        echo "ASPNETCORE_ENVIRONMENT=Production" >> $GITHUB_ENV
        echo "TEST_AGAINST_CONTAINER=true" >> $GITHUB_ENV
        echo "ARTIFACTORY_USERNAME=${{ secrets.ARTIFACTORY_USERNAME }}" >> $GITHUB_ENV
        echo "ARTIFACTORY_PASSWORD=${{ secrets.ARTIFACTORY_PASSWORD }}" >> $GITHUB_ENV

    - name: Make .sh files executable
      run: ./bamboo-specs/scripts/common/set_permission.sh

    - name: Clean Docker
      run: ./bamboo-specs/scripts/common/docker_clean_rm.sh

    - name: Build Docker Image
      run: ./build.sh --target DockerDefault --publishDockerImage=true --should_publish_tags=true --should_publish_package=true

    - name: MSTest Parser
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/*.trx'

    - name: Create Services Artifact
      run: ./bamboo-specs/scripts/common/create_services_artifact.sh

    - name: Docker Cleanup
      run: ./bamboo-specs/scripts/common/docker_clean_rm.sh

    - name: Upload Log Files
      uses: actions/upload-artifact@v2
      with:
        name: log-files
        path: '**/*.log'

    - name: Upload Tag
      uses: actions/upload-artifact@v2
      with:
        name: tag
        path: '**/tag.txt'

    - name: Upload Services Artifact
      uses: actions/upload-artifact@v2
      with:
        name: services-artifact
        path: services-artifact.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: build/artifact_info*.json

  code-provenance:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Checkout provenance repository
      uses: actions/checkout@v2
      with:
        repository: your-org/SRP-Provenance-Github
        path: srp-tools

    - name: Run Provenance
      run: |
        cd srp-tools
        ./Provenance.sh '${{ github.event.head_commit.message }}' '${{ github.run_id }}' '${{ github.run_number }}' '${{ secrets.SRP_CLIENT_ID }}' '${{ secrets.SRP_CLIENT_SECRET }}' '${{ github.sha }}' '${{ github.ref_name }}'

    - name: Docker Cleanup
      run: ./bamboo-specs/scripts/common/docker_clean_rm.sh

notifications:
  pull_request:
    types: [completed]
  webhook:
    url: http://bbs2gh.ssdevrd.com:3000/webhook
  webhook:
    url: http://ws1-build-36-61.vmware.com:8080/api/v1/dags/post_build_dag_example/dagRuns
